#!/bin/zsh

./lemipc --army=1 & ./lemipc --army=4 &

./disp &

sleep 2

for ((i = 0; i < 20; i += 1))
do
    sleep 0.05
    ./lemipc --army=1 &
done

for ((i = 0; i < 20; i += 1))
do
    sleep 0.05
    ./lemipc --army=4 &
done

sleep 6

for ((i = 0; i < 20; i += 1))
do
    sleep 0.05
    ./lemipc --army=1 &
done

for ((i = 0; i < 20; i += 1))
do
    sleep 0.05
    ./lemipc --army=4 &
done
