#!/bin/sh

./lemipc --army=1 & ./lemipc --army=4 &

./disp &

for ((i = 0; i < 15; i++))
do
    sleep 0.01
    ./lemipc --army=1 &
done

for ((i = 0; i < 15; i++))
do
    sleep 0.01
    ./lemipc --army=4 &
done

sleep 4

for ((i = 0; i < 10; i++))
do
    sleep 0.01
    ./lemipc --army=4 &
done

for ((i = 0; i < 10; i++))
do
    sleep 0.01
    ./lemipc --army=1 &
done

for ((i = 0; i < 10; i++))
do
    sleep 0.01
    ./lemipc --army=4 &
done

for ((i = 0; i < 10; i++))
do
    sleep 0.01
    ./lemipc --army=1 &
done

for ((i = 0; i < 10; i++))
do
    sleep 0.01
    ./lemipc --army=4 &
done

for ((i = 0; i < 10; i++))
do
    sleep 0.01
    ./lemipc --army=1 &
done
for ((i = 0; i < 10; i++))
do
    sleep 0.01
    ./lemipc --army=4 &
done

for ((i = 0; i < 10; i++))
do
    sleep 0.01
    ./lemipc --army=1 &
done
